site_name: Bou CSE Resources
site_url: https://mydomain.org/mysite
docs_dir: "obsidian-primary-vault"
theme:
  name: material
  font:
    text: Noto Serif Bengali
    code: Roboto Mono
  logo: assets/logo-bou.png
  favicon: assets/logo-bou.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: deep orange
plugins:
  - get-deps:
      - source: obsidian-primary-vault/bou-cse
        target: docs/obsidian-vault
  - search
  - glightbox
  - obsidian-bridge
# git branch -M main

# git push -u origin main

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        # extra:
        #   social:
        #     - icon: simple/youtube
        #       link: https://youtube.com/@james-willett
        #     - icon: simple/linkedin
        #       link: https://linkedin.com/in/willettjames


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
copyright: Copyright &copy; 2025 Rakibul Hashan
